name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ Asia/Korea }}
          GIST_ID: ${{ 8b3446c1c8134cd563ec2b4228f7d946 }}
          TIMEZONE: Asia/Seoul
